AllCops:
  Includes:
    - '**/*.rake'
    - 'Gemfile'
    - 'Gemfile.devtools'
  Excludes:
    - '**/vendor/**'

# Avoid parameter lists longer than five parameters.
ParameterLists:
  Max: 3
  CountKeywordArgs: true

# Avoid more than `Max` levels of nesting.
BlockNesting:
  Max: 3

# Align with the style guide.
CollectionMethods:
  PreferredMethods:
    collect:  'map'
    inject:   'reduce'
    find:     'detect'
    find_all: 'select'

# Do not force public/protected/private keyword to be indented at the same
# level as the def keyword. My personal preference is to outdent these keywords
# because I think when scanning code it makes it easier to identify the
# sections of code and visually separate them. When the keyword is at the same
# level I think it sort of blends in with the def keywords and makes it harder
# to scan the code and see where the sections are.
AccessControl:
  Enabled: false

LineLength:
  Enabled: true
  Max: 80

# Avoid methods longer than 30 lines of code
MethodLength:
  Max: 3

# Rubocop doesn't allow fine grained per method/class disabling of checks.
# so I'm disabling all the ones that disagree with me *somewhere*

# I mostly agree with this cop, except that { |arg| ... } looks very wrong to
# me. I prefer {|arg| ... } in that case .
SpaceAroundBraces:
  Enabled: false

# Align the parameters of a method call if they span more than one line.
AlignParameters:
  Enabled: false

# Checks for uses of Module#attr.
#
# This is also triggered by instance methods named attr
Attr:
  Enabled: false

# Document classes and non-namespace modules.
#
# The Hexpress module is repeated many times, but only documented in hexpress.rb
Documentation:
  Enabled: false

# The use of eval represents a serious security risk.
#
# Eval is used in the Gemfile to load Devtools
Eval:
  Enabled: false
